# SEE root level "unique_sections.ipynb" for source of this list
PARTS_OF_SPEECH = [
    "noun",
    "verb",
    "adjective",
    "noun 1",
    "noun 2",
    "adverb",
    "pronoun",
    "numeral",
    "proper noun",
    "letter",
    "conjunction",
    "interjection",
    "preposition",
    "determiner",
    "declension",
    "article",
    "contraction",
    "prepositional phrase",
    "verb 1",
    "verb 2",
    "particle",
    "number",
    "symbol",
    "inflection",
    "ordinal number",
]